export default{
    artboard:{
        id:'root',
        label:'Artboard 1',
        children:[],
        currentState:0,
        states:[
            {
                label:'base',
                classes:[],
                text:'',
                style:{
                    position:'relative',
                    width:240,
                    height:320,
                    backgroundColor:'#ffffff',
                    color:'#000'
                }
            }
        ]
    },
    element:{
        id:null,
        label:null,
        type:0,
        currentState:0,
        states:[],
    	locked:false,
        children:[]
    },
    state:{
        id:null,
        name:'base',
        classes:[],
        style:{},
        actions:[],
        text:''
    },
    style:{
        position:'absolute',
        width:0,
        height:0,
        backgroundColor:'#fff',
        borderColor:'#000',
        borderStyle:'solid',
        borderWidth:1,
        boxSizing:'border-box'
    }
}
