export default {
    en:{
        thin:'Thin',
        extraLight:'Extra Light',
        light:'Lignt',
        normal:'Normal',
        medium:'Medium',
        semiBold:'Semi-Bold',
        bold:'Bold',
        extraBold:'Extra-Bold',
        ultraBold:'Ultra-Bold',
        noFontsMessage:'You haven\'t added any fonts to your suitcase',
        enterYourGoogleFontsLinkCode:'Enter your Google Fonts "Standard" linking code',
        googleFonts:'Google Fonts',
        selectedFonts:'Selected Fonts',
        webSafeFonts:'Web Safe Fonts',
        convertDivToTextbox:'Convert element to textbox',
        webSafe:'Web Safe',
        embedded:'Embedded',
        icons:'Icons',
        openFontSuitcase:'Open Font Suitcase',
        fontSuitcase:'Font Suitcase',
        textBox:'Text box',
        findUsOnTwitter:'@pinocchious',
        about:'About',
        canvas:'Canvas',
        layer:'Layer',
        element:'Element',
        welcome:'Welcome',
        createNewDocument:'New Document',
        name:'Name',
        width:'Width',
        height:'Height',
        create:'Create',
        layers:'Layers',
        setFillColor:'Set Fill Color',
        setBorderColor:'Set Border Color',
        setBorderWidth:'Set Border Width',
        new:'New',
        save:'Save',
        locally:' (Locally)',
        createNewFileAndLoseChanges:'Create new file and loose changes?',
        openNewFileAndLoseChanges:'Open new file and loose changes?',
        saveAs:'Save As...',
        saveDocumentAs:'Save Document As',
        doYouWantToOverwrite:'Do you want to overwrite',
        cancel:'Cancel',
        openDocument:'Open Document',
        open:'Open',
        copy:'Copy',
        properties:'Properties',
        top:'Top',
        left:'Left',
        text:'Text',
        textAlign:'Text Align',
        fontSize:'Font Size',
        fontColor:'Font Color',
        fontFamily:'Font Family',
        fontWeight:'Font Weight',
        layout:'Layout',
        padding:'Padding',
        margin:'Margin',
        overflow:'Overflow',
        canvasOverflow:'Canvas Overflow',
        baseStyle:'Base Style',
        hover:'Hover',
        active:'Active',
        textWrap:'Text Wrap',
        align:'Align',
        center:'Center',
        right:'Right',
        justify:'Justify',
        textElementPlaceHolder:'The text you\'d like your element to have',
        hidden:'Hidden',
        scroll:'Scroll',
        auto:'Auto',
        initial:'Initial',
        inherit:'Inherit',
        textStyle:'Text Style',
        italic:'Italic',
        underline:'Underline',
        strikeThrough:'Strike Through',
        noWrap:'No Wrap',
        newLayer:'New Layer',
        removeSelectedLayer:'Remove Selected Layer',
        close:'Close',
        border:'Border',
        borderWidth:'Border Width',
        borderRadius:'Border Radius',
        borderStyle:'Border Style',
        borderColor:'Border Color',
        shadow:'Shadow',
        valueInPixels:'Enter value in pixels',
        none:'None',
        solid:'Solid',
        dashed:'Dashed',
        dotted:'Dotted',
        dropShadow:'Drop Shadow',
        groove:'Groove',
        double:'Double',
        ridge:'Ridge',
        inset:'Inset',
        outset:'Outset',
        style:'Style',
        fill:'Fill',
        blendingMode:'Blending Mode',
        opacity:'Opacity',
        blending:'Blending',
        color:'Color',
        fillColor:'Fill Color',
        image:'Image',
        backgroundImage:'Background Image',
        imageUrl:'ImageUrl',
        browse:'Browse',
        bottom:'Bottom',
        backgroundPosition:'Bg. Position',
        repeat:'Repeat',
        backgroundRepeat:'Bg. Repeat',
        repeatHorizontally:'Repeat Horizontally',
        repeatVertically:'Repeat Vertically',
        dontRepeat:'Don\'t Repeat',
        backgroundSize:'Bg. Size',
        stretch:'Stretch',
        fitToBoundary:'Fit to boundary',
        contained:'Contained within boundary',
        preview:'Preview',
        paste:'Paste',
        duplicateLayer:'Duplicate Layer',
        pasteInPlace:'Paste in Place',
        toolbar:'Toolbar',
        screenStates:'Screen States',
        addState:'Add Screen State',
        state: 'State',
        onMouseOver:'On mouse over',
        onFocus:'On focus',
        actions:'Actions',
        onClickGoTo:'On Click Go To',
        nowhere:'Nowhere',
        transitions:'Transitions',
        effect:'Effect',
        timeMs:'Time (ms)',
        delay:'Delay',
        property:'Property',
        duration:'Duration',
        undo:'Undo',
        redo:'Redo',
        visible:'Visible',
        topOffset:'Top Offset',
        leftOffset:'Left Offset',
        blur:'Blur',
        snapToGrid:'Snap To Grid',
        gridSize:'Grid Size (px)',
        grid:'Grid',
        object:'Object',
        group:'Group',
        ungroup:'Ungroup',
        woot:'woot',
        fontAwesomeIcons:'Font Awesome Icons',
        icon:'Icon',
        insert:'Insert',
        background:'Background',
        gradient:'Gradient',
        type:'type',
        radius:'Radius',
        size:'Size',
        family:'Family',
        suitCaseExplanation:'Add font families to your project by selecting the fonts you need in your suitcase.',
        weight:'weight',
        remove:'Remove',
        cut:'Cut',
        px:'px',
        spread:'Spread',
        position:'Position',
        red:'Red',
        green:'Green',
        blue:'Blue',
        alpha:'Alpha',
        sidebar:'Sidebar',
        drawingStyle:'Drawing Style',
        stroke:'Border',
        strokeWidth:'Border Width',
        selectAll:'Select All',
        ellipse:'Ellipse',
        googleDriveSync:'Google Drive Sync',
        googleDriveDisconnected:'You successfully disconnected your Google Account.',
        googleDriveConnected:'Connection with your Google Drive was successfull, your projects will now sync with your account.',
        loadingAssets:'Loading Assets',
        connectingToGoolgeDrive:'Connecting to Google Drive',
        syncingFiles:'Syncing Files',
        bleed:'Bleed',
        horiz:'H.',
        vert:'V.',
        share:'Share',
        prototypeUrl:'Prototype URL',
        exportingFile:'Exporting File.',
        publish:'Publish',
        signInWithGoogle:'Please sign in with your Google account to view this file.',
        stateName:'New State Name',
        renameState:'Rename State',
        baseStateCannotBeRenamed:'Base state cannot be renamed',
        transition:'Transition',
        renameLayer:'Rename Layer',
        activeBorders:'Active Borders',
        filterMenu:'Filter Menu',
        cloneState:'Clone State',
        deleteState:'Delete State',
        hue:'Hue',
        saturation:'Sat.',
        lightness:'Ligh.',
        geekMode:'Geek Mode',
        resetElementProperties:'Reset Element Properties',
        workspace:'Workspace',
        window:'Window',
        help:'Help',
        file:'File',
        edit:'Edit',
        draggableInputValue:'Draggable Input Values (mobile)'
    }
};
